import fs from 'fs';
import { countries } from '../src/data/countries';

const topojsonNames = JSON.parse(fs.readFileSync('topojson_names.json', 'utf8'));

const mapping: Record<string, string> = {};

// Simple heuristic mapping
const manualMap: Record<string, string> = {
  "Estados Unidos": "United States of America",
  "Reino Unido": "United Kingdom",
  "Rusia": "Russia",
  "Emiratos Árabes Unidos": "United Arab Emirates",
  "República Centroafricana": "Central African Rep.",
  "República Democrática del Congo": "Dem. Rep. Congo",
  "República del Congo": "Congo",
  "Corea del Sur": "South Korea",
  "Corea del Norte": "North Korea",
  "Nueva Zelanda": "New Zealand",
  "Países Bajos": "Netherlands",
  "Bosnia y Herzegovina": "Bosnia and Herz.",
  "Macedonia del Norte": "Macedonia",
  "Arabia Saudita": "Saudi Arabia",
  "Sudáfrica": "South Africa",
  "Birmania": "Myanmar",
  "Suazilandia": "eSwatini",
  "República Checa": "Czechia",
  "República Dominicana": "Dominican Rep.",
  "Guinea Ecuatorial": "Eq. Guinea",
  "Costa de Marfil": "Côte d'Ivoire",
  "Timor Oriental": "Timor-Leste",
  "Bielorrusia": "Belarus",
  "Moldavia": "Moldova",
  "Rumania": "Romania",
  "Kazajistán": "Kazakhstan",
  "Afganistán": "Afghanistan",
  "Irak": "Iraq",
  "Irán": "Iran",
  "Pakistán": "Pakistan",
  "Tayikistán": "Tajikistan",
  "Turkmenistán": "Turkmenistan",
  "Uzbekistán": "Uzbekistan",
  "Kirguistán": "Kyrgyzstan",
  "Azerbaiyán": "Azerbaijan",
  "Bután": "Bhutan",
  "Baréin": "Bahrain",
  "Catar": "Qatar",
  "Singapur": "Singapore",
  "Tailandia": "Thailand",
  "Malasia": "Malaysia",
  "Filipinas": "Philippines",
  "Japón": "Japan",
  "Taiwán": "Taiwan",
  "Alemania": "Germany",
  "Francia": "France",
  "Italia": "Italy",
  "España": "Spain",
  "Brasil": "Brazil",
  "Canadá": "Canada",
  "México": "Mexico",
  "Perú": "Peru",
  "Colombia": "Colombia",
  "Argentina": "Argentina",
  "Chile": "Chile",
  "Ecuador": "Ecuador",
  "Venezuela": "Venezuela",
  "Bolivia": "Bolivia",
  "Paraguay": "Paraguay",
  "Uruguay": "Uruguay",
  "Guyana": "Guyana",
  "Surinam": "Suriname",
  "Panamá": "Panama",
  "Costa Rica": "Costa Rica",
  "Nicaragua": "Nicaragua",
  "Honduras": "Honduras",
  "El Salvador": "El Salvador",
  "Guatemala": "Guatemala",
  "Belice": "Belize",
  "Cuba": "Cuba",
  "Haití": "Haiti",
  "Jamaica": "Jamaica",
  "Bahamas": "Bahamas",
  "Trinidad y Tobago": "Trinidad and Tobago",
  "Marruecos": "Morocco",
  "Argelia": "Algeria",
  "Túnez": "Tunisia",
  "Libia": "Libya",
  "Egipto": "Egypt",
  "Sudán": "Sudan",
  "Sudán del Sur": "S. Sudan",
  "Etiopía": "Ethiopia",
  "Somalia": "Somalia",
  "Kenia": "Kenya",
  "Uganda": "Uganda",
  "Tanzania": "Tanzania",
  "Ruanda": "Rwanda",
  "Burundi": "Burundi",
  "Mozambique": "Mozambique",
  "Madagascar": "Madagascar",
  "Zimbabue": "Zimbabwe",
  "Zambia": "Zambia",
  "Malaui": "Malawi",
  "Angola": "Angola",
  "Namibia": "Namibia",
  "Botsuana": "Botswana",
  "Nigeria": "Nigeria",
  "Níger": "Niger",
  "Chad": "Chad",
  "Camerún": "Cameroon",
  "Gabón": "Gabon",
  "Ghana": "Ghana",
  "Liberia": "Liberia",
  "Sierra Leona": "Sierra Leone",
  "Guinea": "Guinea",
  "Senegal": "Senegal",
  "Malí": "Mali",
  "Burkina Faso": "Burkina Faso",
  "Mauritania": "Mauritania",
  "India": "India",
  "China": "China",
  "Indonesia": "Indonesia",
  "Bangladés": "Bangladesh",
  "Siria": "Syria",
  "Jordania": "Jordan",
  "Líbano": "Lebanon",
  "Israel": "Israel",
  "Yemen": "Yemen",
  "Omán": "Oman",
  "Kuwait": "Kuwait",
  "Turquía": "Turkey",
  "Grecia": "Greece",
  "Bulgaria": "Bulgaria",
  "Serbia": "Serbia",
  "Eslovenia": "Slovenia",
  "Eslovaquia": "Slovakia",
  "Hungría": "Hungary",
  "Austria": "Austria",
  "Suiza": "Switzerland",
  "Bélgica": "Belgium",
  "Polonia": "Poland",
  "Ucrania": "Ukraine",
  "Suecia": "Sweden",
  "Noruega": "Norway",
  "Finlandia": "Finland",
  "Dinamarca": "Denmark",
  "Irlanda": "Ireland",
  "Islandia": "Iceland",
  "Australia": "Australia",
  "Papúa Nueva Guinea": "Papua New Guinea",
  "Fiyi": "Fiji",
  "Islas Salomón": "Solomon Is.",
  "Vanuatu": "Vanuatu",
  "Chipre": "Cyprus",
  "Letonia": "Latvia",
  "Lituania": "Lithuania",
  "Estonia": "Estonia",
  "Armenia": "Armenia",
  "Georgia": "Georgia",
  "Nepal": "Nepal",
  "Sri Lanka": "Sri Lanka",
  "Camboya": "Cambodia",
  "Laos": "Laos",
  "Mongolia": "Mongolia",
  "Yibuti": "Djibouti",
  "Eritrea": "Eritrea",
  "Gambia": "Gambia",
  "Guinea-Bisáu": "Guinea-Bissau",
  "Togo": "Togo",
  "Benín": "Benin",
  "Lesoto": "Lesotho",
  "Portugal": "Portugal",
  "Albania": "Albania",
  "Montenegro": "Montenegro",
  "Croacia": "Croatia",
};

for (const country of countries) {
  if (manualMap[country.name]) {
    mapping[country.name] = manualMap[country.name];
  } else {
    // Try exact match
    const exact = topojsonNames.find((n: string) => n.toLowerCase() === country.name.toLowerCase());
    if (exact) {
      mapping[country.name] = exact;
    } else {
      console.log("Missing mapping for:", country.name);
    }
  }
}

fs.writeFileSync('src/data/mapMapping.ts', `export const mapMapping: Record<string, string> = ${JSON.stringify(mapping, null, 2)};`);
